### ISSUE TITLE
Error when try to change hmm model 

### ISSUE THREAD

**Issue by PRONOVATEK** [respeaker/respeaker_hi#2]
Hi, recently I try to change model, I create folder "es" to make a model in Spanish, I place there files that required to use pocket sphinx (similar in "en" folder), then change on "microphone.py" to in hmm variable, and modify respeaker.dic and keywords.txt but when I try to run app "offline_voice_assistant.py" show the next error: 

Maybe replace config.set_int('-samprate', SAMPLE_RATE) with config.set_float('-samprate', SAMPLE_RATE)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "offline_voice_assistant.py", line 34, in main
    if mic.recognize(keyword='nova'):
  File "/root/respeaker_hi/microphone.py", line 82, in recognize
    self.decoder = self.get_decoder()
  File "/root/respeaker_hi/microphone.py", line 76, in get_decoder
    raise e
RuntimeError: new_Decoder returned -1

Can you suggest to me where is my bad?

regards

**Comment by simpleex** [comment]
Same here with french model in hmm/fr !!
